name: outputs
 
on:
  push:
      branches:
            - master
            - main
   
jobs:
    outputs:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v6
          # - name: output
          #   id: cont
          #   run: |
          #      value=$(cat note.txt  | tr '\n'  ' ')
          #      content=3
          #      hello="welcome"
          #      NAME="hhhhhh"
          #      echo "num=$content"  >> $GITHUB_OUTPUT
          #      echo "val=$value" >> $GITHUB_OUTPUT
          #      echo "wel=$hello"  >> $GITHUB_ENV


          # - name: see content value
          #   if: "${{ steps.cont.outputs.num  == '3' }}"
          #   run: |
          #     echo "${{ steps.cont.outputs.num }}"
          #     echo "${{ steps.cont.outputs.val }}"
          #     echo "${{ env.wel }}"



          # - name: see variable
          #   run: |
          #     echo "${{ vars.NAME }}"
          - name: use custom actions1
            uses: ./.github/actions/cat
            with:
              path: welcome.txt
         
             

          - name: access aws
            uses: ./.github/actions/accessaws
            with:
                aws-access-key: "${{ secrets.ACCESS }}"
                aws-secret-key:  ${{ secrets.SECRET }}
                region: us-east-1
           
          - name: create directory in ec2
            uses: ./.github/actions/ec2-mkdir
            with:
                ip: ${{ secrets.EC2_IP }}
                username: ubuntu
                private_key: "${{ secrets.EC2_KEY }}"
                directory_path: "${{ env.EC2_DIR_PATH }}"
                directory_name: "${{ env.EC2_DIR_NAME }}"

 